
version: "3.7"

networks:
  bif_cs:
    name: bif_cs
    driver: bridge
    driver_opts:
        com.docker.network.bridge.name: bif_cs

volumes:
  app_app:
  app_var_log:
  #app_root:

services:
  cs.cpp:
    extends:
      file: docker-compose.cs.yml
      service: cs
    #build:
    #  target: cs.cpp
    image: code-server-cpp:${ARG_CODE_SERVER_VERSION}-clang-12.0.1
    env_file:
      - cs.env
      - cs.cpp.env
